=begin
#KORONA.entry API v1

#Our api provides access to our entry services

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for KoronaEntryClient::ExternalTicketConfigurationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ExternalTicketConfigurationsApi' do
  before do
    # run before each test
    @api_instance = KoronaEntryClient::ExternalTicketConfigurationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExternalTicketConfigurationsApi' do
    it 'should create an instance of ExternalTicketConfigurationsApi' do
      expect(@api_instance).to be_instance_of(KoronaEntryClient::ExternalTicketConfigurationsApi)
    end
  end

  # unit tests for create_external_ticket_configurations
  # Creates a new external ticket configuration. If an unkown ticket number will be checked and the pattern of the ticket number will be equals to a pattern of a external ticket configuration, a new ticket will be created. The TicketEntry of the external ticket configuration will be copied and adjusted to the new ticket. The newly created ticket is then checked for validity.
  # @param client Identification of executing client.
  # @param body Properties to update of the external ticket configuration.
  # @param [Hash] opts the optional parameters
  # @return [ModelReference]
  describe 'create_external_ticket_configurations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_external_ticket_configuration
  # Deletes the single external ticket configuration.
  # @param client Identification of executing client.
  # @param external_ticket_configuration_id ID to identify the external ticket configuration.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_external_ticket_configuration test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_external_ticket_configuration
  # Returns the external ticket configuration.
  # @param client Identification of executing client.
  # @param external_ticket_configuration_id ID to identify the external ticket configuration.
  # @param [Hash] opts the optional parameters
  # @return [ExternalTicketConfiguration]
  describe 'get_external_ticket_configuration test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_external_ticket_configurations
  # Returns all external ticket configurations
  # @param client Identification of executing client.
  # @param [Hash] opts the optional parameters
  # @return [ExternalTicketConfigurationList]
  describe 'get_external_ticket_configurations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_external_ticket_configuration
  # Updates the single external ticket configuration.
  # @param client Identification of executing client.
  # @param external_ticket_configuration_id ID to identify the external ticket configuration.
  # @param body Properties to update of the external ticket configuration.
  # @param [Hash] opts the optional parameters
  # @return [ModelReference]
  describe 'update_external_ticket_configuration test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
