=begin
#KORONA.entry API v1

#Our api provides access to our entry services

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for KoronaEntryClient::OrganizationalUnitsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrganizationalUnitsApi' do
  before do
    # run before each test
    @api_instance = KoronaEntryClient::OrganizationalUnitsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrganizationalUnitsApi' do
    it 'should create an instance of OrganizationalUnitsApi' do
      expect(@api_instance).to be_instance_of(KoronaEntryClient::OrganizationalUnitsApi)
    end
  end

  # unit tests for create_organizational_unit
  # Creates a new organizational unit.
  # @param client Identification of executing client.
  # @param body Properties to update of the organizational unit.
  # @param [Hash] opts the optional parameters
  # @return [ModelReference]
  describe 'create_organizational_unit test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_organizational_unit
  # Deletes the single organizational unit.
  # @param client Identification of executing client.
  # @param organizational_unit_id ID to identify the organizational unit.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_organizational_unit test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_organizational_unit
  # Returns the single organizational unit.
  # @param client Identification of executing client.
  # @param organizational_unit_id ID to identify the organizational unit.
  # @param [Hash] opts the optional parameters
  # @return [OrganizationalUnit]
  describe 'get_organizational_unit test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_organizational_units
  # Returns all organizational unit
  # @param client Identification of executing client.
  # @param [Hash] opts the optional parameters
  # @return [OrganizationalUnitList]
  describe 'get_organizational_units test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_organizational_unit
  # Updates the single organizational unit.
  # @param client Identification of executing client.
  # @param organizational_unit_id ID to identify the organizational unit.
  # @param body Properties to update of the organizational unit.
  # @param [Hash] opts the optional parameters
  # @return [ModelReference]
  describe 'update_organizational_unit test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
