=begin
#KORONA.entry API v1

#Our api provides access to our entry services

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for KoronaEntryClient::StatisticsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StatisticsApi' do
  before do
    # run before each test
    @api_instance = KoronaEntryClient::StatisticsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StatisticsApi' do
    it 'should create an instance of StatisticsApi' do
      expect(@api_instance).to be_instance_of(KoronaEntryClient::StatisticsApi)
    end
  end

  # unit tests for load_grouped_entries
  # Prepares entries statistically and returns them as a list.
  # @param client Identification of executing client.
  # @param time_from Log time from.
  # @param time_to Log time to.
  # @param ticket_type 
  # @param grouped_entries_type 
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :organizational_unit_numbers 
  # @option opts [Array<String>] :tags 
  # @return [Array<StatisticGroupedEntry>]
  describe 'load_grouped_entries test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
